Repository Codiologoist/DigitalTwins, pull requests merged in 2025-01, with the labels that each got.

#59 Fist time run restriction and Testing run
  .github/workflows/CI.yml
  client/src/App.tsx
  client/src/api.ts
  client/src/components/DoctorTable.tsx
  client/src/components/Modal.tsx
  client/src/components/MonitorComponent.tsx
  client/src/components/PatientTable.tsx
  client/src/hooks/usePatientData.ts
  client/src/types/types.ts
  client/src/utils.ts
  client/src/views/AdminsPage.tsx
  client/src/views/DoctorsPage.tsx
  package.json
  server/decryption/requirements.txt
  server/decryption/src/copy_latest.py
  server/decryption/src/decryptor.py
  server/decryption/src/folder_extraction.py
  server/decryption/src/main.py
  server/src/controllers/patientController.ts
  server/src/index.ts
  server/src/models/Patient.ts
  server/src/routes/patient.ts
  server/src/services/utils.ts
  server/src/tests/digital_twins.postman_collection.json
Labels: Enhancement, Feature, High-priority

#60 58 update readme
  LICENSE
  README.md
  client/README.md
  server/README.md
Labels: Documentation

#61 56 Fix & Finish plotting
  client/src/components/MonitorComponent.tsx
  client/src/components/PatientSignalsComponent.tsx
  client/src/components/RowComponent.tsx
  client/src/components/ValueDisplayComponent.tsx
  client/src/hooks/usePatientData.ts
  client/src/types/types.ts
  server/decryption/src/main.py
  server/src/services/utils.ts
Labels: Enhancement

#66 Add signals
  client/index.html
  client/src/App.tsx
  client/src/assets/ecg.png
  client/src/components/MonitorComponent.tsx
  client/src/components/PatientSignalsComponent.tsx
  client/src/components/PatientTable.tsx
  client/src/components/PrivateRouteComponent.tsx
  client/src/components/RowComponent.tsx
  client/src/components/ValueDisplayComponent.tsx
  client/src/hooks/usePatientData.ts
  client/src/types/types.ts
Labels: Enhancement
